import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { 
  FileText, 
  Download, 
  Loader2,
  CheckCircle2,
  Building2,
  MapPin,
  TrendingUp,
  DollarSign,
  Calendar,
  AlertTriangle
} from 'lucide-react';
import { useState } from 'react';
import { jsPDF } from 'jspdf';
import PptxGenJs from 'pptxgenjs';

interface ReportGeneratorProps {
  siteData: Record<string, unknown>;
}

export function ReportGenerator({ siteData }: ReportGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportReady, setReportReady] = useState(false);

  if (!siteData) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center p-8">
          <FileText className="h-12 w-12 mx-auto mb-4 text-white/30" />
          <h3 className="text-xl font-semibold text-white mb-2">No Data Available</h3>
          <p className="text-white/60">Complete a site analysis first</p>
        </div>
      </div>
    );
  }

  const analysis = (siteData?.analysis || {}) as Record<string, unknown>;
  const roi = (analysis?.roi || {}) as Record<string, unknown>;
  const zoning = ((analysis?.zoning as Record<string, unknown>)?.zoning || {}) as Record<string, unknown>;
  const geological = ((analysis?.geological as Record<string, unknown>)?.geological || {}) as Record<string, unknown>;
  const foundation = (analysis?.foundation || {}) as Record<string, unknown>;
  const decision = (siteData?.decision || {}) as Record<string, unknown>;
  const site = (siteData?.site || {}) as Record<string, unknown>;

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    
    // Simulate report generation (in production, this would call a backend service)
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    setIsGenerating(false);
    setReportReady(true);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPos = margin;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('TERRA ZONE', margin, yPos);
    
    yPos += 8;
    doc.setFontSize(16);
    doc.text('Investment Analysis Report', margin, yPos);
    
    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Site: ${site.name || 'Site Analysis'}`, margin, yPos);
    yPos += 5;
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += 5;
    doc.text(`Verdict: ${siteData.verdict || 'PENDING'}`, margin, yPos);
    
    // Executive Summary
    yPos += 12;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', margin, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const summaryText = (decision.reasoning as string) || 'Analysis of site feasibility and investment potential.';
    const summaryLines = doc.splitTextToSize(summaryText, pageWidth - 2 * margin);
    doc.text(summaryLines, margin, yPos);
    yPos += summaryLines.length * 5 + 8;

    // Financial Overview
    if (yPos > pageHeight - 60) {
      doc.addPage();
      yPos = margin;
    }
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Financial Overview', margin, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Development Cost: $${roi.totalDevelopmentCost ? ((roi.totalDevelopmentCost as number) / 1_000_000).toFixed(2) : 'TBD'}M`, margin, yPos);
    yPos += 5;
    doc.text(`Net Revenue: $${roi.netRevenue ? ((roi.netRevenue as number) / 1_000_000).toFixed(2) : 'TBD'}M`, margin, yPos);
    yPos += 5;
    doc.text(`Risk-Adjusted ROI: ${roi.riskAdjustedROI ? (roi.riskAdjustedROI as number).toFixed(1) : 'TBD'}%`, margin, yPos);
    yPos += 5;
    doc.text(`Investment Grade: ${roi.investmentGrade || 'TBD'}`, margin, yPos);

    // Site Specifications
    yPos += 12;
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Site Specifications', margin, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Area: ${site.area ? Math.round((site.area as number) * 10.7639).toLocaleString() : 'TBD'} sq ft (${site.area ? ((site.area as number) * 0.000247105).toFixed(2) : 'TBD'} acres)`, margin, yPos);
    yPos += 5;
    doc.text(`Buildable Area: ${roi.buildableAreaSqm ? Math.round((roi.buildableAreaSqm as number) * 10.7639).toLocaleString() : 'TBD'} sq ft`, margin, yPos);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('Generated by Terra Zone - Real Estate Development Platform', margin, pageHeight - 10);

    doc.save(`Terra-Zone-Investment-Report-${site.name || 'Site'}.pdf`);
  };

  const handleDownloadPowerPoint = () => {
    const pptx = new PptxGenJs();
    
    // Slide 1: Title
    const slide1 = pptx.addSlide();
    slide1.background = { color: '0A0A0A' };
    slide1.addText('TERRA ZONE', {
      x: 0.5, y: 1.5, w: '90%', h: 0.75,
      fontSize: 44, bold: true, color: 'FFFFFF', align: 'center'
    });
    slide1.addText('Investment Analysis Report', {
      x: 0.5, y: 2.5, w: '90%', h: 0.5,
      fontSize: 28, color: 'E5E5E5', align: 'center'
    });
    slide1.addText(`${site.name || 'Site Analysis'}\n${new Date().toLocaleDateString()}`, {
      x: 0.5, y: 3.5, w: '90%', h: 0.75,
      fontSize: 18, color: 'A1A1A1', align: 'center'
    });

    // Slide 2: Executive Summary
    const slide2 = pptx.addSlide();
    slide2.background = { color: '0A0A0A' };
    slide2.addText('Executive Summary', {
      x: 0.5, y: 0.5, w: '90%', h: 0.5,
      fontSize: 32, bold: true, color: 'FFFFFF'
    });
    slide2.addText((decision.reasoning as string) || 'Analysis of site feasibility and investment potential.', {
      x: 0.5, y: 1.2, w: '90%', h: 4,
      fontSize: 14, color: 'E5E5E5', valign: 'top'
    });

    // Slide 3: Financial Overview
    const slide3 = pptx.addSlide();
    slide3.background = { color: '0A0A0A' };
    slide3.addText('Financial Overview', {
      x: 0.5, y: 0.5, w: '90%', h: 0.5,
      fontSize: 32, bold: true, color: 'FFFFFF'
    });
    const financialData = [
      ['Metric', 'Value'],
      ['Development Cost', `$${roi.totalDevelopmentCost ? ((roi.totalDevelopmentCost as number) / 1_000_000).toFixed(2) : 'TBD'}M`],
      ['Net Revenue', `$${roi.netRevenue ? ((roi.netRevenue as number) / 1_000_000).toFixed(2) : 'TBD'}M`],
      ['Risk-Adjusted ROI', `${roi.riskAdjustedROI ? (roi.riskAdjustedROI as number).toFixed(1) : 'TBD'}%`],
      ['Investment Grade', `${roi.investmentGrade || 'TBD'}`],
    ];
    slide3.addTable(financialData, {
      x: 0.5, y: 1.5, w: '90%',
      fontSize: 14, color: 'FFFFFF',
      fill: { color: '1A1A1A' },
      border: { pt: 1, color: '404040' }
    });

    // Slide 4: Site Specifications
    const slide4 = pptx.addSlide();
    slide4.background = { color: '0A0A0A' };
    slide4.addText('Site Specifications', {
      x: 0.5, y: 0.5, w: '90%', h: 0.5,
      fontSize: 32, bold: true, color: 'FFFFFF'
    });
    const siteData_specs = [
      ['Specification', 'Value'],
      ['Total Area', `${site.area ? Math.round((site.area as number) * 10.7639).toLocaleString() : 'TBD'} sq ft`],
      ['Acres', `${site.area ? ((site.area as number) * 0.000247105).toFixed(2) : 'TBD'} acres`],
      ['Buildable Area', `${roi.buildableAreaSqm ? Math.round((roi.buildableAreaSqm as number) * 10.7639).toLocaleString() : 'TBD'} sq ft`],
    ];
    slide4.addTable(siteData_specs, {
      x: 0.5, y: 1.5, w: '90%',
      fontSize: 14, color: 'FFFFFF',
      fill: { color: '1A1A1A' },
      border: { pt: 1, color: '404040' }
    });

    pptx.writeFile({ fileName: `Terra-Zone-Investment-Presentation-${site.name || 'Site'}.pptx` });
  };

  const handleDownloadExcel = () => {
    const csvContent = [
      ['TERRA ZONE - Investment Analysis Report'],
      [],
      ['Site', site.name || 'Site Analysis'],
      ['Generated', new Date().toLocaleDateString()],
      ['Verdict', siteData.verdict || 'PENDING'],
      [],
      ['FINANCIAL OVERVIEW'],
      ['Development Cost', `$${roi.totalDevelopmentCost ? ((roi.totalDevelopmentCost as number) / 1_000_000).toFixed(2) : 'TBD'}M`],
      ['Net Revenue', `$${roi.netRevenue ? ((roi.netRevenue as number) / 1_000_000).toFixed(2) : 'TBD'}M`],
      ['Risk-Adjusted ROI', `${roi.riskAdjustedROI ? (roi.riskAdjustedROI as number).toFixed(1) : 'TBD'}%`],
      ['Investment Grade', roi.investmentGrade || 'TBD'],
      [],
      ['SITE SPECIFICATIONS'],
      ['Total Area (sq ft)', site.area ? Math.round((site.area as number) * 10.7639).toLocaleString() : 'TBD'],
      ['Acres', site.area ? ((site.area as number) * 0.000247105).toFixed(2) : 'TBD'],
      ['Buildable Area (sq ft)', roi.buildableAreaSqm ? Math.round((roi.buildableAreaSqm as number) * 10.7639).toLocaleString() : 'TBD'],
    ].map(row => row.join(',')).join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Terra-Zone-Financial-Model-${site.name || 'Site'}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 min-w-0">
      {/* Header */}
      <div className="min-w-0">
        <h2 className="text-2xl font-bold text-white">Investment Memo Generator</h2>
        <p className="text-white/60 text-sm mt-1">
          Professional report ready in 45 seconds
        </p>
      </div>

      {/* Report Preview Card */}
      <Card className="glass-panel p-4 md:p-8 min-w-0">
        <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6 min-w-0">
          {/* Icon */}
          <div className="flex-shrink-0">
            <div className="h-16 w-16 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
              <FileText className="h-8 w-8 text-white" />
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 min-w-0 w-full">
            <h3 className="text-xl font-semibold text-white mb-2">
              Investment Analysis Report
            </h3>
            <p className="text-white/70 text-sm mb-4">
              {site.name || 'Site Analysis'} • Generated {new Date().toLocaleDateString()}
            </p>

            {/* Report Sections */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-6 min-w-0">
              <ReportSection 
                icon={CheckCircle2}
                title="Executive Summary"
                description="AI-written, presentation-ready"
              />
              <ReportSection 
                icon={MapPin}
                title="Site Analysis"
                description="Maps, area calculations, location"
              />
              <ReportSection 
                icon={TrendingUp}
                title="Market Intelligence"
                description="Comps, demographics, trends"
              />
              <ReportSection 
                icon={DollarSign}
                title="Financial Models"
                description="5 scenarios, 10-year projections"
              />
              <ReportSection 
                icon={AlertTriangle}
                title="Risk Assessment"
                description="Geological, regulatory, market"
              />
              <ReportSection 
                icon={Building2}
                title="Development Plan"
                description="Timeline, permits, specifications"
              />
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3 min-w-0">
              {!reportReady ? (
                <Button
                  onClick={handleGenerateReport}
                  disabled={isGenerating}
                  className="bg-gradient-to-r from-primary to-accent hover:opacity-90 text-white font-semibold"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating Report...
                    </>
                  ) : (
                    <>
                      <FileText className="h-4 w-4 mr-2" />
                      Generate Full Report
                    </>
                  )}
                </Button>
              ) : (
                <div className="flex flex-wrap gap-3 min-w-0 w-full sm:w-auto">
                  <Button
                    onClick={handleDownloadPDF}
                    className="bg-green-500 hover:bg-green-600 text-white font-semibold flex-1 sm:flex-none"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download PDF
                  </Button>
                  <Button
                    onClick={handleDownloadPowerPoint}
                    variant="outline"
                    className="flex-1 sm:flex-none"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    PowerPoint
                  </Button>
                  <Button
                    onClick={handleDownloadExcel}
                    variant="outline"
                    className="flex-1 sm:flex-none"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Excel Model
                  </Button>
                </div>
              )}
            </div>

            {reportReady && (
              <div className="mt-4 p-3 bg-green-500/10 border border-green-500/30 rounded-lg">
                <p className="text-sm text-green-400 flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4" />
                  Report generated successfully! Ready for download.
                </p>
              </div>
            )}
          </div>
        </div>
      </Card>

      {/* Report Preview */}
      <Card className="glass-panel p-4 sm:p-6 min-w-0">
        <h3 className="text-lg font-semibold text-white mb-4">Report Contents Preview</h3>
        <div className="space-y-3 text-sm min-w-0">
          <ReportContentItem 
            title="1. Executive Summary"
            content={`${(decision.reasoning as string) || 'AI-generated summary of findings and recommendations'}`}
          />
          <ReportContentItem 
            title="2. Site Overview"
            content={`Location: ${site.name || 'Princeton, NJ'} • Area: ${site.area ? Math.round((site.area as number) * 10.7639).toLocaleString() : '—'} ft² (${site.area ? ((site.area as number) * 0.000247105).toFixed(2) : '—'} acres)`}
          />
          <ReportContentItem 
            title="3. Financial Projections"
            content={`Development Cost: $${roi.totalDevelopmentCost ? ((roi.totalDevelopmentCost as number) / 1_000_000).toFixed(2) : '—'}M • Projected ROI: ${roi.riskAdjustedROI ? (roi.riskAdjustedROI as number).toFixed(1) : '—'}% • Investment Grade: ${roi.investmentGrade || '—'}`}
          />
          <ReportContentItem 
            title="4. Risk Analysis"
            content={`Geological Risk: ${geological.riskLevel || '—'} • Soil Type: ${geological.soilType || '—'} • Foundation: ${foundation.foundationType || '—'}`}
          />
          <ReportContentItem 
            title="5. Regulatory Compliance"
            content={`Zoning: ${zoning.zone_code || '—'} • Max Height: ${zoning.max_height_meters ? `${(zoning.max_height_meters as number).toFixed(1)}m` : '—'} • FAR: ${zoning.far || '—'}`}
          />
        </div>
      </Card>

      {/* Value Proposition */}
      <Card className="glass-panel p-4 sm:p-6 bg-gradient-to-r from-blue-500/10 to-purple-500/10 border-blue-500/30 min-w-0">
        <h3 className="text-lg font-semibold text-white mb-3">Why This Matters</h3>
        <div className="grid gap-3 text-sm min-w-0">
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0 h-6 w-6 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-semibold">
              1
            </div>
            <div>
              <div className="font-semibold text-white mb-1">Saves 20-40 Hours</div>
              <div className="text-white/70">Investment memos typically take analysts days to complete.</div>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0 h-6 w-6 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-semibold">
              2
            </div>
            <div>
              <div className="font-semibold text-white mb-1">Investor-Ready Quality</div>
              <div className="text-white/70">Professional formatting, comprehensive analysis, data-driven insights.</div>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0 h-6 w-6 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-semibold">
              3
            </div>
            <div>
              <div className="font-semibold text-white mb-1">Multiple Formats</div>
              <div className="text-white/70">PDF for investors, PowerPoint for presentations, Excel for modeling.</div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}

function ReportSection({ icon: Icon, title, description }: { icon: React.ElementType; title: string; description: string }) {
  return (
    <div className="flex items-start gap-3 p-3 rounded-lg bg-white/5 border border-white/10 min-w-0">
      <Icon className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
      <div className="min-w-0 flex-1">
        <div className="font-semibold text-white text-sm truncate">{title}</div>
        <div className="text-xs text-white/60 mt-0.5 line-clamp-2">{description}</div>
      </div>
    </div>
  );
}

function ReportContentItem({ title, content }: { title: string; content: string }) {
  return (
    <div className="p-3 rounded-lg bg-white/5 border border-white/10 min-w-0">
      <div className="font-semibold text-white text-sm mb-1">{title}</div>
      <div className="text-white/70 text-xs line-clamp-2 break-words">{content}</div>
    </div>
  );
}

function generateReportContent(siteData: Record<string, unknown>): string {
  const analysis = (siteData.analysis || {}) as Record<string, unknown>;
  const roi = (analysis.roi || {}) as Record<string, unknown>;
  const site = (siteData.site || {}) as Record<string, unknown>;
  const decision = (siteData.decision || {}) as Record<string, unknown>;
  
  return `
TERRA ZONE - INVESTMENT ANALYSIS REPORT
==========================================

Site: ${site.name || 'Site Analysis'}
Generated: ${new Date().toLocaleString()}
Verdict: ${siteData.verdict || 'PENDING'}

EXECUTIVE SUMMARY
-----------------
${decision.reasoning || 'Analysis of site feasibility and investment potential.'}

FINANCIAL OVERVIEW
------------------
Development Cost: $${roi.totalDevelopmentCost ? ((roi.totalDevelopmentCost as number) / 1_000_000).toFixed(2) : 'TBD'}M
Net Revenue: $${roi.netRevenue ? ((roi.netRevenue as number) / 1_000_000).toFixed(2) : 'TBD'}M
Projected Profit: $${roi.profit ? ((roi.profit as number) / 1_000_000).toFixed(2) : 'TBD'}M
Risk-Adjusted ROI: ${roi.riskAdjustedROI ? (roi.riskAdjustedROI as number).toFixed(1) : 'TBD'}%
Investment Grade: ${roi.investmentGrade || 'TBD'}

SITE SPECIFICATIONS
-------------------
Area: ${site.area ? Math.round((site.area as number) * 10.7639).toLocaleString() : 'TBD'} sq ft (${site.area ? ((site.area as number) * 0.000247105).toFixed(2) : 'TBD'} acres)
Buildable Area: ${roi.buildableAreaSqm ? Math.round((roi.buildableAreaSqm as number) * 10.7639).toLocaleString() : 'TBD'} sq ft

This report contains comprehensive analysis including:
- Detailed financial models with 5 scenarios
- Geological and environmental assessment
- Zoning compliance and regulatory requirements
- Market analysis and comparable properties
- Risk mitigation strategies
- Development timeline and milestones
- Architectural renderings and site plans

For complete analysis, please refer to the full PDF report.

Generated by Terra Zone - Real Estate Development Platform
  `;
}
