// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4ntj1x4gog8637m.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG50ajF4NGdvZzg2MzdtIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzY0MjY0MDAsImV4cCI6MjA5MjAwMjQwMH0.AV6lB1M6lo0PUwey-Kshf4U_miFLSwESNMiZGQIKsBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
