// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oihfkdhozaujasrjmeif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9paGZrZGhvemF1amFzcmptZWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4MTU2NjgsImV4cCI6MjA5NjM5MTY2OH0.pJTPqmWUMHGXXCd4Kfa8uieaOCQKoMxNJxN_d4IWqDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
